### ISSUE TITLE
Add a `rustfmt` Ci task

### ISSUE THREAD

**Issue by dlrobertson** [dlrobertson/capsicum-rs#13]
It would be nice to have a `rustfmt` task as well, but we can do this in a follow up since it requires a `cargo fmt` run.

_Originally posted by @dlrobertson in https://github.com/dlrobertson/capsicum-rs/pull/12#discussion_r1020256852_

**Comment by dlrobertson** [comment]
Steps to fix:

 1) run `cargo fmt` on the repo
 2) Follow [Checking Style on a CI Server](https://github.com/rust-lang/rustfmt#checking-style-on-a-ci-server) to run `cargo fmt` in our CI.

**Comment by asomers** [comment]
Fixed by #14 .
