### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by dlrobertson** [dlrobertson/capsicum-rs#2]
Travis doesn't support FreeBSD, so this could be difficult.

**Comment by asomers** [comment]
Difficult with Travis, but quite easy with Cirrus CI.  If you're still maintaining this crate, I can help you setup CI.

**Comment by asomers** [comment]
I can create a Cirrus CI configuration for you if you want.  Just follow the instructions at https://cirrus-ci.org/guide/quick-start/ but stop when you get to "Post-installation" and I'll submit a PR to take care of the rest.

**Comment by dlrobertson** [comment]
>  Just follow the instructions at https://cirrus-ci.org/guide/quick-start/

Done!
