### ISSUE TITLE
Use I/O Safety

### ISSUE THREAD

**Issue by asomers** [dlrobertson/capsicum-rs#31]
Rust 1.63.0 introduces I/O safety.  `RawFd` (just a wrapper around `i32`) gets replaced by `OwnedFd` to track file ownership.  It's a very nice improvement, and I think capscium should take advantage.
https://blog.rust-lang.org/2022/08/11/Rust-1.63.0.html#rust-ownership-for-raw-file-descriptorshandles-io-safety

**Comment by dlrobertson** [comment]
👍 this would be very nice!
