### ISSUE TITLE
Release 0.3.0, please

### ISSUE THREAD

**Issue by asomers** [dlrobertson/capsicum-rs#54]
After PR #50 and #51 merge, would you please build a new release?  That will allow me to satisfy "cargo audit" on downstream crates.

**Comment by dlrobertson** [comment]
Will do

**Comment by asomers** [comment]
Thanks.  And FTR @dlrobertson just added me as an owner on crates.io.  Shall I make the release myself, then?

**Comment by dlrobertson** [comment]
> Thanks. And FTR @dlrobertson just added me as an owner on crates.io. Shall I make the release myself, then?

If you have time and need it ASAP. I will not be available to post a release until this evening. Scheduled all the meetings today 😆

**Comment by asomers** [comment]
I think I'll be able to do it today, but I realize now that there's one more change I want to make here first: update the ctor and syn dependencies to reduce duplicate dependencies downstream.

**Comment by asomers** [comment]
@dlrobertson I just published the release.  Could you now please relax branch protection rules so I can push the tag?  I wish there were a better way to do it, but I don't know of one.

**Comment by asomers** [comment]
Whatever you did allowed me to push tags, but not changes.  I'll try making a PR for the sole change.

**Comment by asomers** [comment]
Fixed by #61
