### ISSUE TITLE
Need cap_net bindings

### ISSUE THREAD

**Issue by asomers** [dlrobertson/capsicum-rs#63]
For a new project, I need bindings to [cap_net(3)](https://man.freebsd.org/cgi/man.cgi?query=cap_net).  Do you think they should be a part of this repository or standalone?  I'll start work in a standalone repo, but merge it here if you think that's best.

**Comment by asomers** [comment]
Here's what I've got so far.  https://github.com/asomers/capsicum-net

**Comment by dlrobertson** [comment]
Real cool! I'll definitely follow your progress on it... Definitely as you get started its probably easier to work in a separate repo. If you'd like a review on something, definitely feel free to ping me. If it helps, a project like that would make sense as a workspace member.

**Comment by asomers** [comment]
I'm finished capsicum-net as much as I need it.  Having done so, I feel that it's fine to live in its own repository.  I don't think the Casper API will change rapidly enough to demand that they be merged into the same repo.
