### ISSUE TITLE
Unable to add rights with different indices

### ISSUE THREAD

**Issue by krasenyp** [dlrobertson/capsicum-rs#89]
Hello and thank you for this crate. I'm very excited to incorporate Capsicum into the software I write. Unfortunately, I faced an issue when trying to add rights with different indices:
```rust
let rights = RightsBuilder::new(Right::Bind)
        .add(Right::Read)
        .add(Right::Event)
        .finalize();
```
When I run the program I get: `Assertion failed: (i >= 0), function cap_rights_vset, file /usr/src/sys/kern/subr_capability.c, line 188.`. I know this library uses `cap_rights_set` and such error shouldn't happen. Or am I generally misunderstanding how rights can be set and combined?

I'll be thankful if you help me resolve the issue.

**Comment by asomers** [comment]
I'm glad you like the crate!  This issue is already fixed by #80 , but there hasn't been a new release since then.  I'd like to make a release soon.
